### ISSUE TITLE
Read parameters from query string 

### ISSUE THREAD

**Issue by joshuabambrick** [samj1912/CookieS#4]
Give a running CookieS UI, support reading from the URI query string the cookiecutter name (and potentially the target repo and the target github org) so that these parameters can be pre-populated in the UI. This would allow pre-populated links from a cookie cutter to the UI.

**Comment by joshuabambrick** [comment]
For maximal awareness: https://en.wikipedia.org/wiki/Query_string

**Comment by joshuabambrick** [comment]
The UI could automatically update the URI as these values are entered in the UI by the user. This could make it clearer that the URI is share-able. Alternatively, a 'share' button could work.

**Comment by sambhav** [comment]
Fixed in the latest commit to master
